# -*- mode: ruby -*-
# vi: set ft=ruby : set ts=4 : set sw=4 : set sts

Vagrant.configure(2) do |config|
    config.vm.box = "ubuntu/trusty32"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.cpus = 4
        vb.memory = "4096"
    end
end
